-- Recipes Table Schema
-- Run this in your Supabase SQL Editor

-- 1. Create recipes table
CREATE TABLE IF NOT EXISTS recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL, -- 'New', 'Half-done', 'Done'
  cover_image_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create recipe_ingredients junction table
CREATE TABLE IF NOT EXISTS recipe_ingredients (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  recipe_id BIGINT REFERENCES recipes(id) ON DELETE CASCADE,
  ingredient_id TEXT NOT NULL, -- References ingredients(id) which is text based on your JSON
  quantity TEXT, -- Optional: for future use like "200g" or "1 cup"
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_recipes_status ON recipes(status);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_recipe_id ON recipe_ingredients(recipe_id);
CREATE INDEX IF NOT EXISTS idx_recipe_ingredients_ingredient_id ON recipe_ingredients(ingredient_id);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE recipes ENABLE ROW LEVEL SECURITY;
ALTER TABLE recipe_ingredients ENABLE ROW LEVEL SECURITY;

-- 5. Create RLS Policies
-- Allow public read access
CREATE POLICY "Enable read access for all users" ON recipes FOR SELECT USING (true);
CREATE POLICY "Enable read access for all users" ON recipe_ingredients FOR SELECT USING (true);

-- Allow authenticated users to insert/update/delete (or all users for now based on your previous cart schema)
CREATE POLICY "Enable write access for all users" ON recipes FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON recipes FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON recipes FOR DELETE USING (true);

CREATE POLICY "Enable write access for all users" ON recipe_ingredients FOR INSERT WITH CHECK (true);
CREATE POLICY "Enable update access for all users" ON recipe_ingredients FOR UPDATE USING (true);
CREATE POLICY "Enable delete access for all users" ON recipe_ingredients FOR DELETE USING (true);

-- 6. Setup Storage for Recipe Images
-- Note: You might need to create the bucket 'recipe-images' manually in the dashboard if this SQL doesn't work due to permissions
INSERT INTO storage.buckets (id, name, public) 
VALUES ('recipe-images', 'recipe-images', true)
ON CONFLICT (id) DO NOTHING;

-- Storage Policies
CREATE POLICY "Give public access to recipe images" ON storage.objects
  FOR SELECT USING (bucket_id = 'recipe-images');

CREATE POLICY "Enable upload access for all users" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'recipe-images');

CREATE POLICY "Enable update access for all users" ON storage.objects
  FOR UPDATE USING (bucket_id = 'recipe-images');

CREATE POLICY "Enable delete access for all users" ON storage.objects
  FOR DELETE USING (bucket_id = 'recipe-images');

-- 7. Auto-update updated_at timestamp
CREATE TRIGGER update_recipes_updated_at
    BEFORE UPDATE ON recipes
    FOR EACH ROW
    EXECUTE FUNCTION update_shopping_cart_updated_at_column(); -- Reusing the function from cart schema
